# Generated by Django 3.2.7 on 2021-09-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0050_delete_brandmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='image',
            field=models.FileField(upload_to='products', verbose_name='image'),
        ),
    ]
