# Generated by Django 3.2.7 on 2021-09-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0051_alter_productmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='image22',
            field=models.FileField(null=True, upload_to='products', verbose_name='image22'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='image33',
            field=models.FileField(null=True, upload_to='products', verbose_name='image33'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='image44',
            field=models.FileField(null=True, upload_to='products', verbose_name='image44'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='image55',
            field=models.FileField(null=True, upload_to='products', verbose_name='image55'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='image66',
            field=models.FileField(null=True, upload_to='products', verbose_name='image66'),
        ),
    ]
