# Generated by Django 3.2.7 on 2021-09-28 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0059_alter_productmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='image22',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='image33',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='image44',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='image55',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='image66',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='image77',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='image88',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='image99',
        ),
    ]
