# Generated by Django 3.2.7 on 2021-09-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0060_auto_20210928_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=29)),
                ('image22', models.FileField(blank=True, null=True, upload_to='products', verbose_name='image22')),
                ('image33', models.FileField(blank=True, null=True, upload_to='products', verbose_name='image33')),
                ('image44', models.FileField(blank=True, null=True, upload_to='products', verbose_name='image44')),
                ('image55', models.FileField(blank=True, null=True, upload_to='products/textures', verbose_name='image55')),
                ('image66', models.FileField(blank=True, null=True, upload_to='products/textures', verbose_name='image66')),
                ('image77', models.FileField(blank=True, null=True, upload_to='products/texture', verbose_name='image77')),
                ('image88', models.FileField(blank=True, null=True, upload_to='products', verbose_name='image88')),
                ('image99', models.FileField(blank=True, null=True, upload_to='products', verbose_name='image99')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Threed',
                'verbose_name_plural': 'Threeds',
            },
        ),
    ]
