# Generated by Django 3.2.7 on 2021-09-28 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0065_auto_20210928_1832'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ThreedModel',
        ),
    ]
