# Generated by Django 3.2.7 on 2021-09-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0070_auto_20210928_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='image',
            field=models.FileField(null=True, upload_to='products1', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='image22',
            field=models.FileField(blank=True, null=True, upload_to='products2', verbose_name='image22'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='image33',
            field=models.FileField(blank=True, null=True, upload_to='products3', verbose_name='image33'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='image44',
            field=models.FileField(blank=True, null=True, upload_to='products4/textures', verbose_name='image44'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='image55',
            field=models.FileField(blank=True, null=True, upload_to='products5/textures', verbose_name='image55'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='image66',
            field=models.FileField(blank=True, null=True, upload_to='products6/textures', verbose_name='image66'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='image77',
            field=models.FileField(blank=True, null=True, upload_to='products7', verbose_name='image77'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='image88',
            field=models.FileField(blank=True, null=True, upload_to='products8', verbose_name='image88'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='image99',
            field=models.FileField(blank=True, null=True, upload_to='products9', verbose_name='image99'),
        ),
    ]
